import type { HeroSlide, HeroSlideInput } from "./types";

/** DB が空 or エラー時のフォールバック */
export const DEFAULT_HERO_SLIDES: HeroSlide[] = [
  {
    id: "default-main",
    sortOrder: 0,
    enabled: true,
    badge: "ジサップ 開発スタジオ",
    title: "AIにコードを作ってもらって、貼るだけでアプリが完成。",
    subtitle: "サーバー設定もデータベースも不要。使い慣れたAIのコードを貼るだけで即公開！",
    ctaEnabled: true,
    ctaLabel: "アプリ開発スタジオへ",
    ctaHref: "/playground",
    layout: "two_column",
    theme: "studio",
    visualType: "studio",
    bgPattern: "grid",
    featuredAppIds: [],
  },
  {
    id: "default-summer",
    sortOrder: 1,
    enabled: true,
    badge: "新企画：夏休みの自由研究・宿題に",
    title: "夏休みの自由研究・工作は、自分だけのアプリを作って提出しよう！",
    subtitle:
      "AIと一緒に『生活を便利にするツール』や『オリジナルゲーム』を作るだけ。アイデアを形にする体験で、周りと差がつく自由研究に！",
    ctaEnabled: true,
    ctaLabel: "作り方ガイドを見る",
    ctaHref: "/guide/summer-research",
    layout: "theme",
    theme: "summer",
    visualType: "summer",
    bgPattern: "dots",
    featuredAppIds: [],
  },
  {
    id: "default-mobile",
    sortOrder: 2,
    enabled: true,
    badge: "スマホ対応",
    title: "スマホ1台で、アイデアをそのままアプリに。",
    subtitle: "パソコンがなくても大丈夫。通学中や移動時間のチャットから、数分で自分だけのツールを公開！",
    ctaEnabled: false,
    ctaLabel: null,
    ctaHref: null,
    layout: "two_column",
    theme: "cyan",
    visualType: "phone",
    bgPattern: "grid",
    featuredAppIds: [],
  },
  {
    id: "default-requests",
    sortOrder: 3,
    enabled: true,
    badge: "開発依頼掲示板",
    title: "欲しいアプリは『作って！』と頼んでみよう。",
    subtitle: "「こんなツールがあったらいいな」を掲示板に投げるだけ。みんなのアイデアで作る開発コミュニティ。",
    ctaEnabled: false,
    ctaLabel: null,
    ctaHref: null,
    layout: "two_column",
    theme: "amber",
    visualType: "requests",
    bgPattern: "none",
    featuredAppIds: [],
  },
];

export const EMPTY_SLIDE_INPUT: HeroSlideInput = {
  sortOrder: 0,
  enabled: true,
  badge: "",
  title: "",
  subtitle: "",
  ctaEnabled: false,
  ctaLabel: "",
  ctaHref: "",
  layout: "two_column",
  theme: "studio",
  visualType: "studio",
  bgPattern: "grid",
  featuredAppIds: [],
};
